# -*- coding: utf-8 -*-
"""fix_praktikum04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iJ52s3as5LlItm_4MmsRT_O87MdrCnuy

*PRAKTIKUM BAR CHART*

** KELOMPOK 18:**
*   NAMA (NIM)
*   NAMA (NIM)
*   NAMA (NIM)
"""

import matplotlib.pyplot as plt

#data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science',
]

jumlah_mahasiswa = [120, 150, 100, 80]

#membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color = ['blue', 'orange', 'green', 'red'])
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.title('Jumlah Mahasiswa Per Jurusan')
plt.show()

"""a. basic bar chart dengan **matplotlib**"""

import matplotlib.pyplot as plt

#data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science',
]

jumlah_mahasiswa = [120, 150, 100, 80]

#membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color = ['blue', 'orange', 'green', 'red'])
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.title('Jumlah Mahasiswa Per Jurusan')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""b. basic chart dengan **kustomisasi**"""

import matplotlib.pyplot as plt

#data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science',
]

jumlah_mahasiswa = [120, 150, 100, 80]

#membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color = ['blue', 'orange', 'green', 'red'])
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.title('Jumlah Mahasiswa Per Jurusan')
plt.xticks(rotation=45)

#menambahkan label pada barang
for i, v in enumerate(jumlah_mahasiswa):
  plt.text(i, v + 5, str(v), ha='center')

plt.show()

"""**c. Multiple Bar Chart**"""

import matplotlib.pyplot as plt

#data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science',
]

jumlah_mahasiswa = [120, 150, 100, 80]
jumlah_mahasiswa_2024 = [110, 140, 95, 85]

x = range(len(jurusan))
width = 0.4

plt.bar(x, jumlah_mahasiswa, width, label='2023', color='orange')
plt.bar([p + width for p in x], jumlah_mahasiswa_2024, width=width,
        label='2024', color='skyblue')

#membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color = ['blue', 'orange', 'green', 'red'])
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.title('Jumlah Mahasiswa Per Jurusan')
plt.xticks(rotation=45)
plt.xticks([p + width/2 for p in x], jurusan)
plt.legend()


plt.show()

"""**d. basic chart untuk meliaht pola dan tren**"""

import matplotlib.pyplot as plt

#data
jurusan = ['Ilmu Komputer', 'Teknik Informatika', 'Sistem Informasi', 'Data Science']
tahun =['2019', '2020', '2021', '2022', '2023']
data = {
    'Ilmu Komputer' : [100, 110, 120, 130, 140],
    'Teknik Informatika' : [120, 120, 132, 145, 160],
    'Sistem Informasi' : [90, 95, 100, 105, 110],
    'Data Science' : [70, 75, 80, 85,90],

}
width = 0.2
x = range(len(tahun))

#visualisasi masing"jurusan
plt.bar(x, data['Ilmu Komputer'], width=width, label='Ilmu Komputer', color='blue')
plt.bar([p + width for p in x],
        data['Sistem Informasi'], width=width, label='Sistem Informasi', color='green')
plt.bar([p + width *2 for p in x],
        data['Teknik Informatika'], width=width, label='Teknik Informatika', color='orange')
plt.bar([p + width *3 for p in x],
        data['Data Science'], width=width, label='Data Science', color='red')

#detail grafik
plt.title('Tren Jumlah Mahasiswa Per Jurusan (2019 VS 2023)')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks([p + width for p in x], tahun)
plt.legend()

plt.show()