# -*- coding: utf-8 -*-
"""Praktikum4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbqLP9vDup72chhWLDtiBM0qt8CqtCta

**PRAKTIKUM BAR CHART**

**Kelompok 18**


*   Apriyanto (0110222256)
*   Deva Lubna Listya (0110222258)
*   Raydino Situmeang (Raydino Situmeang)
"""

import matplotlib.pyplot as plt

# data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science'
]

jumlah_mahasiswa = [120, 150, 100, 80]

# membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color=['blue', 'orange','green', 'red'])
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.title('Jumlah Mahasiswa Per Jurusan')
plt.show()

"""**a. Basic Bar Chart dengan Matplotlib**"""

import matplotlib.pyplot as plt

# data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science'
]

jumlah_mahasiswa = [120, 150, 100, 80]

# membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color=['blue', 'orange','green', 'red'])
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.title('Jumlah Mahasiswa per Jurusan')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""**b. Kustomi**"""

import matplotlib.pyplot as plt

# data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science'
]

jumlah_mahasiswa = [120, 150, 100, 80]

# membuat basic bar chart
plt.bar(jurusan, jumlah_mahasiswa, color=['blue', 'orange','green', 'red'])
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.title('Jumlah Mahasiswa per Jurusan')
plt.xticks(rotation=45)

# menambahkan label pada batang
for i, v in enumerate(jumlah_mahasiswa):
    plt.text(i, v + 2, str(v), ha='center')
plt.show()

"""**c. Menambahkan Multiple Bar Chart**"""

import matplotlib.pyplot as plt

# data
jurusan = [
    'Ilmu Komputer',
    'Teknik Informatika',
    'Sistem Informasi',
    'Data Science'
]

jumlah_mahasiswa = [120, 150, 100, 80]
jumlah_mahasiswa_2024 = [110, 140, 85, 90] # Added a value to match length of jurusan

x = range(len(jurusan))
width_= 0.4

plt.bar(x, jumlah_mahasiswa, width_, label='2024', color='orange')
plt.bar([p + width_ for p in x], jumlah_mahasiswa_2024, width=width_,
        label='2024', color='skyblue')
# membuat basic bar chart
plt.title('Jumlah Mahasiswa Per Jurusan (2023 vs 2024)')
plt.xlabel('Jurusan')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks(rotation=45)
plt.xticks([p + width_/2 for p in x], jurusan)
plt.legend()
plt.show()

"""**d. Basic Bar Chart untuk Melihat Pola dan Tren**"""

# data
jurusan = ['Ilmu Komputer', 'Teknik Informatika', 'Sistem Informasi', 'Data Science']
tahun = ['2019', '2020', '2021', '2022', '2023']
data ={
    'Ilmu Komputer' : [100, 110, 120, 130, 140],
    'Teknik Informatika' : [120, 120, 132, 145, 160],
    'Sistem Informasi' : [90, 95, 100, 105, 110],
    'Data Science' : [70, 75, 80, 85, 90]
}
# Membuat Bar Chart untuk masing masing jurusan
width = 0.2
x = range(len(tahun))

# visualisasi masing" jurusan
plt.bar(x, data['Ilmu Komputer'], width=width, label='Ilmu Komputer', color='blue')
plt.bar([p + width for p in x], data['Sistem Informasi'], width=width, label='Sitem Informasi', color='green')
plt.bar([p + width *2 for p in x], data['Teknik Informatika'], width=width, label='Teknik Informatika', color='orange')
plt.bar([p + width *3 for p in x], data['Data Science'], width=width, label='Data Science', color='purple')

# Memberikan detail pada grafik
plt.title('Tren Jumlah Mahasiswa Per Jurusan (2019-2023)')
plt.xlabel('Tahun')
plt.ylabel('Jumlah Mahasiswa')
plt.xticks(rotation=45)
plt.xticks([p + width * 1.5 for p in x], tahun)
plt.legend()
plt.show()

