# -*- coding: utf-8 -*-
"""praktikum modul 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XG8DgG0hUX3vfDFEZakW8n-kaJ2vy26q

# **Praktikum 6 Matplotlip Stacked Vertikal Bar Chart-  Kelompok 18**

---


**1. Stacked Vertikal Bar Chart**

A. Stacked Vertical Bar Chart dengan Matplotlib
"""

import matplotlib.pyplot as plt
import numpy as np

# Data
stores = ['Store A', 'Store B', 'Store C']
male_population = [150, 200, 180]
female_population = [120, 230, 170]

# Posisi bar
x = np.arange(len(stores))

# Membuat stacked bar chart
plt.bar(x, male_population, label='Male', color='blue')
plt.bar(x, female_population, bottom=male_population, label='Female', color='pink')

# Pengaturan grafik
plt.xlabel('Stores')
plt.ylabel('Population')
plt.title('Population by Gender and Store')
plt.xticks(x, stores)
plt.legend()

# Tampilkan grafik
plt.show()

"""B. Kustomisasi Stacked Vertical Bar Chart"""

import matplotlib.pyplot as plt
import numpy as np

# Data
stores = ['Store A', 'Store B', 'Store C']
male_population = [150, 200, 180]
female_population = [120, 230, 170]

# Posisi bar
x = np.arange(len(stores))

# Membuat stacked bar chart
plt.bar(x, male_population, label='Male', color='blue')
plt.bar(x, female_population, bottom=male_population, label='Female', color='pink')

# Pengaturan grafik
plt.xlabel('Stores')
plt.ylabel('Population')
plt.title('Population by Gender and Store')
plt.xticks(x, stores)
plt.legend()

# Menambahkan label data
for i in range(len(x)):
    plt.text(x[i], male_population[i] / 2,
             str(male_population[i]),
             ha='center', color='white')

    plt.text(x[i], male_population[i] + (female_population[i] / 2),
             str(female_population[i]),
             ha='center', color='black')

# Tampilkan grafik
plt.show()

"""

---

"""