# -*- coding: utf-8 -*-
"""Praktikum06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o64I842SC01zvR34ldi3HP8kn63ahus0
"""

import matplotlib.pyplot as plt
import numpy as np

# Data
stores = ['Store A', 'Store B', 'Store C']
male_population = [150, 200, 180]
female_population = [120, 230, 170]

# Bar positions
x = np.arange(len(stores))

# Membuat Stacked Bar Chart
plt.bar(x, male_population, label='Male', color='blue')
plt.bar(x, female_population, bottom=male_population, label='Female', color='pink')

# Penyesuaian
plt.xlabel('Stores')
plt.ylabel('Population')
plt.title('Population by Gender and Store')
plt.xticks(x, stores)
plt.legend()

# Tampilkan
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data
stores = ['Store A', 'Store B', 'Store C']
male_population = [150, 200, 180]
female_population = [120, 230, 170]

# Bar positions
x = np.arange(len(stores))

# Membuat Stacked Bar Chart
plt.bar(x, male_population, label='Male', color='blue')
plt.bar(x, female_population, bottom=male_population, label='Female', color='pink')

# Penyesuaian
plt.xlabel('Stores')
plt.ylabel('Population')
# Catatan: Bagian bawah gambar terpotong,
# biasanya dilanjutkan dengan plt.title(), plt.xticks(), plt.legend(), dan plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data tambahan untuk periode berbeda
stores = ['Store A', 'Store B', 'Store C']
q1_male = [150, 180, 160]
q1_female = [140, 200, 180]
q2_male = [170, 190, 175]
q2_female = [130, 210, 160]
q3_male = [160, 185, 170]
q3_female = [135, 195, 165]
q4_male = [155, 175, 168]
q4_female = [125, 205, 158]

x = np.arange(len(stores))

# Lebar batang
bar_width = 0.2

# Multiple Stacked Bar Chart
plt.bar(x - bar_width * 1.5, q1_male, label='Q1 Male', color='lightblue', width=bar_width)
plt.bar(x - bar_width * 1.5, q1_female, bottom=q1_male, label='Q1 Female', color='pink', width=bar_width)

plt.bar(x - bar_width / 2, q2_male, label='Q2 Male', color='blue', width=bar_width)
plt.bar(x - bar_width / 2, q2_female, bottom=q2_male, label='Q2 Female', color='red', width=bar_width)

plt.bar(x + bar_width / 2, q3_male, label='Q3 Male', color='green', width=bar_width)
plt.bar(x + bar_width / 2, q3_female, bottom=q3_male, label='Q3 Female', color='yellow', width=bar_width)

plt.bar(x + bar_width * 1.5, q4_male, label='Q4 Male', color='purple', width=bar_width)
plt.bar(x + bar_width * 1.5, q4_female, bottom=q4_male, label='Q4 Female', color='orange', width=bar_width)

# Penyesuaian
plt.xlabel('Stores')
plt.ylabel('Population')
plt.title('Population by Gender and Store (Quarterly)')
plt.xticks(x, stores)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left') # Legenda diletakkan di luar grafik

plt.tight_layout()
plt.show()

