# -*- coding: utf-8 -*-
"""Praktikum5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LFR2Xgd_bmiw8b-AUhUkG4QNWvfP15Dy

# **Praktikum 5 Visualisasi Data**

## **Kelompok 18**

*   Raydino Situmeang (0110222278)
*   Apriyanto(0110222256)
*   Deva Lubna Listya(0110222258)

### **1.Import Library**
"""

import matplotlib.pyplot as plt

"""### **2.Buat Dataset**"""

suhu = [20, 22, 24, 26, 28, 30, 32, 34, 36]
penjualan = [50, 60, 70, 90, 100, 110, 130, 150, 180]

"""### **3.Basic Scatter Plot**"""

plt.scatter(suhu, penjualan)
plt.title("hubungan penjualan es dengan suhu")
plt.xlabel("suhu")
plt.ylabel('Hubungan Penjualan Es Krim')
plt.show()

"""### **4.Kustomisasi Scatter Plot**"""

plt.scatter(suhu, penjualan, color='orange', s=100, edgecolor='black', alpha=0.7)
plt.title('Hubungan Penjualan Es Krim dengan Suhu')
plt.xlabel('Suhu')
plt.ylabel('Penjualan Es Krim')
plt.grid(True)
plt.show()

"""### **5.Multiple Scatter Plot**"""

# dataset suhu
suhu = [20, 22, 24, 26, 28, 30, 32, 34, 36]

# dataset penjualan
penjualan_weekdays = [50, 60, 70, 80, 90, 100, 110, 120, 130]
penjualan_weekend = [60, 70, 80, 100, 110, 120, 140, 160, 200]

plt.scatter(suhu, penjualan_weekdays, color="green", label="Hari Kerja", s=80)
plt.scatter(suhu, penjualan_weekend, color="purple", label="Akhir Pekan", s=80)
plt.title('Hubungan Penjualan')
plt.xlabel('Suhu')
plt.ylabel('Penjualan Es Krim')
plt.legend()
plt.show()

"""### **6.Melihat Hubungan Data dengan Beberapa Variabel**"""

# dataset
suhu = [20, 22, 24, 26, 28, 30, 32, 34, 36]
penjualan = [50, 60, 70, 90, 100, 110, 130, 150, 180]

# dataset tambahan
Kelembapan = [60, 65, 70, 75, 80, 85, 90, 95, 100]
ukuran_titik = [200, 220, 240, 260, 280, 300, 320, 340, 360]

# Kustomisasi Scatter Plot
plt.scatter(suhu, penjualan, c=Kelembapan, s=ukuran_titik, cmap='coolwarm', alpha=0.6)
plt.title('Hubungan Penjualan, Suhu, dan Kelembapan')
plt.xlabel('Suhu')
plt.ylabel('Penjualan Es Krim')
plt.colorbar(label='Kelembapan')
plt.show()

"""### **7.3D Scatter Plot**"""

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# dataset suhu
suhu = [20, 22, 24, 26, 28, 30, 32, 34, 36]

# dataset penjualan
penjualan_weekdays = [50, 60, 70, 80, 90, 100, 110, 120, 130]
penjualan_weekend = [60, 70, 80, 100, 110, 120, 140, 160, 200]

# 3D Scatter Pot
fig = plt.figure(figsize=(15, 13))
ax = fig.add_subplot(111, projection='3d')

ax.scatter(suhu, penjualan_weekdays, penjualan_weekend,
           color='orange', s=80, label='Data Penjualan') # Corrected 's' parameter and added 'label'

ax.set_title('Hubungan Penjualan Es Krim dan Suhu (3D ver)')
ax.set_xlabel('Suhu')
ax.set_ylabel('Penjualan Weekdays')
ax.set_zlabel('Penjualan Weekends')
ax.legend()
plt.show()

