# -*- coding: utf-8 -*-
"""tugas praktikum modul 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XeWDNDkpOAdAoJm_hR5KWIzBmBA2kL8

**Kelompok 18**
1.   Raydino Situmeang (0110222278)
2.   Apriyanto(0110222256)
3. Deva Lubna Listya(0110222258)

**1. Import Library**
"""

import matplotlib.pyplot as plt

"""**2. Buat Dataset**"""

suhu = (20, 24, 26, 28, 40, 42, 43, 45, 35)
penjualan = (50, 60, 70, 80, 90, 100, 110, 130, 150)

"""**3. Basic Scatter Plot**"""

plt.scatter(suhu, penjualan)
plt.title("hubungan penjualan es dengan suhu")
plt.xlabel("suhu")
plt.ylabel('penjualan Es krim')
plt.show()

"""**4. kustomisasi scatter plot**"""

plt.scatter(suhu, penjualan, color= "orange")
plt.title

plt.scatter(suhu, penjualan)
plt.title("hubungan penjualan es dengan suhu")
plt.xlabel("suhu")
plt.ylabel('penjualan Es krim')
plt.show()

"""**5. multiple scatter plot**"""

#dataset suhu
suhu = (20, 24, 26, 28, 40, 42, 43, 45, 35)

#dataset penjualan
perjalanan_weekdays = (50, 60, 70, 80, 90, 100, 110, 130, 150)
perjalanan_weekends = (10, 20, 30, 40, 50, 60, 70, 80, 90)

plt.scatter(suhu, perjalanan_weekdays, color="orange", label="Hari Kerja", s= 58)
plt.scatter(suhu, perjalanan_weekends, color="green", label="Hari Libur", s= 56)
plt.title("hubungan penjualan es dengan suhu")
plt.xlabel("suhu")
plt.ylabel('penjualan Es krim')
plt.legend()
plt.show()

"""**6. melihat hubungan data dengan beberapa variabel**"""

#dataset
suhu = (20, 24, 26, 28, 40, 42, 43, 45, 35)
penjualan = (50, 60, 70, 80, 90, 100, 110, 130, 150) # Adjusted to 9 elements

#dataset
kelembapan = (60, 70, 80, 90, 100, 110, 130, 150, 190) # Converted to tuple
ukuran_titik = (280, 220, 210, 250, 200, 260, 290, 240, 270) # Converted to tuple and adjusted to 9 elements

#kustomisasi scatter plot
plt.scatter(suhu, penjualan, c=kelembapan, s=ukuran_titik, cmap='Purples', alpha=0.6)
plt.title("hubungan penjualan es dengan suhu")
plt.xlabel("suhu")
plt.ylabel('penjualan Es krim')
plt.colorbar(label= "kelembapan (%)")
plt.show()

"""**7. 3D scatter plot**"""

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
#datat suhu
suhu = (20, 24, 26, 28, 40, 42, 43, 45, 35)

#dataset penjualan
perjalanan_weekdays = (50, 60, 70, 80, 90, 100, 110, 130, 150)
perjalanan_weekends = (10, 20, 30, 40, 50, 60, 70, 80, 90)

#3D scatter plot
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(suhu, perjalanan_weekdays, perjalanan_weekends,
           color = 'orange', s=48, label ='Data Penjualan')

ax.set_title("hubungan penjualan Es Krim dan Suhu (3D)")
ax.set_xlabel("suhu")
ax.set_ylabel("perjalanan weekdays")
ax.set_zlabel("perjalanan weekends")
ax.legend()
plt.show()