# -*- coding: utf-8 -*-
"""Google Colab Pertemuan7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cj2I1ezTbdQtBcXOQv1vRqbekd6Xb7ky

# Horizontal Bar Chart & Stacked Horizontal Bar Chart

### 1. Import Library
"""

import matplotlib.pyplot as plt
import numpy as np

"""### 2. Dataset"""

# data penjualan smartphone
brands = ['Samsung', 'Iphone', 'Vivo', 'Oppo']
sales_2023 = [500, 700, 300, 400]
sales_2024 = [550, 750, 350, 450]
sales_2025 = [600, 800, 400, 500]

"""### 3. Grafik Basic (Horizontal & Stacked Horizontal Bar Chart)"""

y_pos = np.arange(len(brands))

# ====================================
# 1. BASIC HORIZONTAL BAR CHART (2023)
# ====================================
fig1, ax1 = plt.subplots()
ax1.barh(brands, sales_2023)
ax1.set_title('Horizontal Bar Chart - 2023')
ax1.set_xlabel('Jumlah Penjualan')
ax1.set_ylabel('Merk')

plt.show()

# =================================================
# 2. BASIC STACKED HORIZONTAL BAR CHART (2023 & 2024)
# =================================================
fig2, ax2 = plt.subplots()
ax2.barh(brands, sales_2023, label='2023')
ax2.barh(brands, sales_2024, left=sales_2023, label='2024')

ax2.set_title('Penjualan Smartphone Stacked (2023 & 2025)')
ax2.set_xlabel('Jumlah Penjualan')
ax2.set_ylabel('Merk')
ax2.legend()

plt.show()

"""### 4. Grafik Kustomisasi (Horizontal & Stacked Horizontal Bar Chart)"""

y_pos = np.arange(len(brands))
colors = ['gold', 'skyblue', 'coral', 'lightgreen']

# =====================================
# 1. CUSTOM HORIZONTAL BAR CHART (2023)
# =====================================
fig3, ax3 = plt.subplots()
ax3.barh(brands, sales_2023, color=colors, edgecolor='black', height=0.6)
ax3.set_title('Penjualan Smartphone Tahun 2023 (Customized)')
ax3.set_xlabel('Jumlah Penjualan')
ax3.set_ylabel('Merk')
ax3.grid(axis='x', linestyle='--', alpha=0.7)

# menampilkan label nilai di bar chart
for i, v in enumerate(sales_2023):
    ax3.text(v + 10, i, str(v), va='center')

plt.show()

# ==================================================
# 2. CUSTOM STACKED HORIZONTAL BAR CHART (2023–2025)
# ==================================================
fig4, ax4 = plt.subplots()
ax4.barh(brands, sales_2023, color='lightcoral', edgecolor='black',label='2023')
ax4.barh(brands, sales_2024, left=sales_2023, color='lightskyblue',  edgecolor='black', label='2024')

ax4.set_title('Penjualan Smartphone Tahun 2023 (Stacaked - Customized)')
ax4.set_xlabel('Jumlah Penjualan')
ax4.set_ylabel('Merk')
ax4.legend()
ax4.grid(axis='x', linestyle='--', alpha=0.5)

# menampilkan label nilai di bar chart
total_sales = np.array(sales_2023) + np.array(sales_2024) + np.array(sales_2025)

for i, v in enumerate(total_sales):
    ax4.text(v + 10, i, str(v), va='center')

plt.show()

"""### 5. Grafik Multiple (Horizontal & Stacked Horizontal Bar Chart)"""

y_pos = np.arange(len(brands))

# ===============================================
# 1. MULTIPLE HORIZONTAL BAR CHART (2023 vs 2024)
# ===============================================
fig5, ax5 = plt.subplots()
ax5.barh(y_pos - 0.2, sales_2023, color='skyblue', height=0.4, label='2023')
ax5.barh(y_pos + 0.2, sales_2024, color='salmon', height=0.4, label='2024')

ax5.set_yticks(y_pos, brands)
ax5.set_title('Penjualan Smartphone 2023 vs 2024')
ax5.set_xlabel('Jumlah Penjualan')
ax5.set_ylabel('Merk')
ax5.legend()

plt.show()

# ====================================================
# 2. MULTIPLE STACKED HORIZONTAL BAR CHART (2023–2025)
# ====================================================
fig6, ax6 = plt.subplots()
ax6.barh(y_pos, sales_2023, color='skyblue', label='2023')
ax6.barh(y_pos, sales_2024, left=sales_2023, color='salmon', label='2024')
ax6.barh(y_pos, sales_2025, left=np.array(sales_2023) + np.array(sales_2024), color='lightgreen', label='2025')

ax6.set_yticks(y_pos, brands)
ax6.set_title('Penjualan Smartphone 2023 vs 2025 (Stacked)')
ax6.set_xlabel('Jumlah Penjualan')
ax6.set_ylabel('Merk')
ax6.legend()

plt.show()

"""# Pie Chart & Area Chart

### 1. Dataset
"""

# data partisipasi siswa (pie chart)
kegiatan = ['Olahraga', 'Seni', 'Musik', 'Debat']
persentase = [30, 20, 25, 25]

# data kelompok 1
kegiatan_1 = ['Olahraga', 'Seni']
persentase_1 = [40, 60]

# data kelompok 2
kegiatan_2 = ['Musik', 'Debat']
persentase_2 = [50, 50]

# daa penjualan bulanan (area chart)
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep']
shoes = [500, 600, 700, 800, 650, 700, 750, 800, 850]
sandals = [300, 350, 400, 450, 500, 480, 520, 550, 600]
socks = [200, 250, 300, 350, 400, 380, 420, 450, 500]

"""### 2. Grafik Basic (Pie Chart dan Area Chart)"""

# ===============
# BASIC PIE CHART
# ===============
fig1, ax1 = plt.subplots()
ax1.pie(persentase, labels=kegiatan, autopct='%1.1f%%', startangle=140)
ax1.set_title('Persentase Partisipasi Siswa dalam Kegiatan Ekstrakurikuler')
plt.show()

# ================
# BASIC AREA CHART
# ================
fig2, ax2 = plt.subplots()
ax2.fill_between(months, shoes, alpha=0.4)
ax2.set_title('Basic Area Chart: Monthly Sales')
ax2.set_xlabel('Months')
ax2.set_ylabel('Units Sold')
plt.show()

"""### 3. Grafik Kustomisasi (Pie Chart dan Area Chart)"""

# ================
# CUSTOM PIE CHART
# ================
colors = ['gold', 'lightskyblue', 'lightcoral', 'lightgreen']
explode = (0.1, 0, 0, 0)

fig3, ax3 = plt.subplots()
ax3.pie(persentase, labels=kegiatan, colors=colors, autopct='%1.1f%%', startangle=140, explode=explode, shadow=True)
ax3.set_title('Persentase Partisipasi Siswa (Customized)')
ax3.legend(kegiatan, loc='best')
plt.show()

# =================
# CUSTOM AREA CHART
# =================
fig4, ax4 = plt.subplots()
ax4.fill_between(months, shoes, color='lightblue', alpha=0.5, label='Shoes')
ax4.fill_between(months, sandals, color='lightgreen', alpha=0.5, label='Sandals')
ax4.set_title('Customized Area Chart: Monthly Sales')
ax4.set_xlabel('Months')
ax4.set_ylabel('Units Sold')
ax4.grid(axis='y', linestyle='--', alpha=0.6)
ax4.legend()
plt.show()

"""### 4. Grafik Multiple (Pie Chart dan Area Chart)"""

# ==================
# MULTIPLE PIE CHART
# ==================
fig5, axs = plt.subplots(1, 2, figsize=(12, 6))

axs[0].pie(persentase_1, labels=kegiatan_1, autopct='%1.1f%%', startangle=140)
axs[0].set_title('Partisipasi: Kelompok 1')

axs[1].pie(persentase_2, labels=kegiatan_2, autopct='%1.1f%%', startangle=140)
axs[1].set_title('Partisipasi: Kelompok 2')

plt.suptitle('Perbandingan Partisipasi Siswa')
plt.show()

# ===================
# MULTIPLE AREA CHART
# ===================
fig6, ax6 = plt.subplots()
ax6.fill_between(months, shoes, color='lightblue', alpha=0.4, label='Shoes')
ax6.fill_between(months, sandals, color='lightgreen', alpha=0.4, label='Sandals')
ax6.fill_between(months, socks, color='orange', alpha=0.4, label='Socks')

ax6.set_title('Multiple Area Chart: Monthly Sales')
ax6.set_xlabel('Months')
ax6.set_ylabel('Units Sold')
ax6.legend()
ax6.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

